---
service: up-settle

frameworkVersion: '2'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  transaction:
    handler: index.handleTransaction
    events:
      - http:
          path: /
          method: post
